package lab.wavgrafx.com.dumaguetehealthline.model

class ClinicModel (

    val Fname: String = "",
    val Mname: String = "",
    val Lname: String = "",
    val Gender: String = "",
    val Degree: String = "",
    val Practice: String = "",
    val CNum: String = "",
    val Cert: String = "",
    val Address: String = "",
    val Mon: Boolean = false,
    val Tue: Boolean = false,
    val Wed: Boolean = false,
    val Thu: Boolean = false,
    val Fri: Boolean = false,
    val Sat: Boolean = false,
    val Sun: Boolean = false,
    val MonOpen: String = "",
    val MonClose: String = "",
    val TueOpen: String = "",
    val TueClose: String = "",
    val WedOpen: String = "",
    val WedClose: String = "",
    val ThuOpen: String = "",
    val ThuClose: String = "",
    val FriOpen: String = "",
    val FriClose: String = "",
    val SatOpen: String = "",
    val SatClose: String = "",
    val SunOpen: String = "",
    val SunClose: String = "",
    val Break1: Boolean = false,
    val Break2: Boolean = false,
    val Break1start: String = "",
    val Break1end: String = "",
    val Break2start: String = "",
    val Break2end: String = "",
    val MaxPat:String = "",
    val AllowedBookDays:String = "",
    val Creator: String = ""
)